// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using XDonation.Data;

#nullable disable

namespace XDonation.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("XDonation.Models.Dispensation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("StockBatchId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StockBatchId");

                    b.ToTable("Dispensations", (string)null);
                });

            modelBuilder.Entity("XDonation.Models.DonationVoucher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DonorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DonorType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("ReceiptDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ValidatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("VoucherNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("VoucherNumber")
                        .IsUnique();

                    b.ToTable("DonationVouchers", (string)null);
                });

            modelBuilder.Entity("XDonation.Models.DonationVoucherLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Barcode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("BatchNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CodeBarresFabricant")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Dci")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("DonationVoucherId")
                        .HasColumnType("int");

                    b.Property<int?>("DrugId")
                        .HasColumnType("int");

                    b.Property<string>("DrugName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("StockBatchId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DonationVoucherId");

                    b.HasIndex("DrugId");

                    b.HasIndex("StockBatchId");

                    b.ToTable("DonationVoucherLines", (string)null);
                });

            modelBuilder.Entity("XDonation.Models.Drug", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Barcode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CodeBarresFabricant")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Dci")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Form")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("Barcode")
                        .IsUnique()
                        .HasFilter("[Barcode] IS NOT NULL");

                    b.HasIndex("CodeBarresFabricant")
                        .IsUnique()
                        .HasFilter("[CodeBarresFabricant] IS NOT NULL");

                    b.ToTable("Drugs", (string)null);
                });

            modelBuilder.Entity("XDonation.Models.StockBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Barcode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("BatchNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DrugId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("InitialQuantity")
                        .HasColumnType("int");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPsychotrope")
                        .HasColumnType("bit");

                    b.Property<string>("Store")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("DrugId");

                    b.ToTable("StockBatches", (string)null);
                });

            modelBuilder.Entity("XDonation.Models.Dispensation", b =>
                {
                    b.HasOne("XDonation.Models.StockBatch", "StockBatch")
                        .WithMany("Dispensations")
                        .HasForeignKey("StockBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StockBatch");
                });

            modelBuilder.Entity("XDonation.Models.DonationVoucherLine", b =>
                {
                    b.HasOne("XDonation.Models.DonationVoucher", "DonationVoucher")
                        .WithMany("Lines")
                        .HasForeignKey("DonationVoucherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("XDonation.Models.Drug", "Drug")
                        .WithMany("VoucherLines")
                        .HasForeignKey("DrugId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("XDonation.Models.StockBatch", "StockBatch")
                        .WithMany()
                        .HasForeignKey("StockBatchId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("DonationVoucher");

                    b.Navigation("Drug");

                    b.Navigation("StockBatch");
                });

            modelBuilder.Entity("XDonation.Models.StockBatch", b =>
                {
                    b.HasOne("XDonation.Models.Drug", "Drug")
                        .WithMany("StockBatches")
                        .HasForeignKey("DrugId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drug");
                });

            modelBuilder.Entity("XDonation.Models.DonationVoucher", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("XDonation.Models.Drug", b =>
                {
                    b.Navigation("StockBatches");

                    b.Navigation("VoucherLines");
                });

            modelBuilder.Entity("XDonation.Models.StockBatch", b =>
                {
                    b.Navigation("Dispensations");
                });
#pragma warning restore 612, 618
        }
    }
}
