// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using XpertPharm5Donation.Data;

#nullable disable

namespace XpertPharm5Donation.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("XpertPharm5Donation.Models.Dispensation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("StockBatchId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StockBatchId");

                    b.ToTable("Dispensations", (string)null);
                });

            modelBuilder.Entity("XpertPharm5Donation.Models.DonationVoucher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DonorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DonorType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("ReceiptDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ValidatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("VoucherNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("VoucherNumber")
                        .IsUnique();

                    b.ToTable("DonationVouchers", (string)null);
                });

            modelBuilder.Entity("XpertPharm5Donation.Models.DonationVoucherLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Barcode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("BatchNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Dci")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("DonationVoucherId")
                        .HasColumnType("int");

                    b.Property<int?>("DrugId")
                        .HasColumnType("int");

                    b.Property<string>("DrugName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("StockBatchId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DonationVoucherId");

                    b.HasIndex("DrugId");

                    b.HasIndex("StockBatchId");

                    b.ToTable("DonationVoucherLines", (string)null);
                });

            modelBuilder.Entity("XpertPharm5Donation.Models.Drug", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Dci")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Form")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.ToTable("Drugs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dci = "Amoxicilline / Acide clavulanique",
                            Form = "Comprimé",
                            Name = "AUGMENTIN 1G COMPRIME"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dci = "Paracétamol",
                            Form = "Comprimé",
                            Name = "PARACETAMOL 500MG COMPRIME"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dci = "Acide acétylsalicylique",
                            Form = "Comprimé",
                            Name = "ASPIRINE 500MG COMPRIME"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dci = "Paracétamol",
                            Form = "Comprimé",
                            Name = "DOLIPRANE 1000MG COMPRIME"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dci = "Amoxicilline",
                            Form = "Gélule",
                            Name = "AMOXICILLINE 500MG GELULE"
                        });
                });

            modelBuilder.Entity("XpertPharm5Donation.Models.StockBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Barcode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("BatchNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DrugId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("InitialQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DrugId");

                    b.ToTable("StockBatches", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Barcode = "3400921845603",
                            BatchNumber = "LOT001",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DrugId = 1,
                            ExpirationDate = new DateTime(2027, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InitialQuantity = 500
                        },
                        new
                        {
                            Id = 2,
                            Barcode = "3400936563017",
                            BatchNumber = "LOT002",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DrugId = 2,
                            ExpirationDate = new DateTime(2026, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InitialQuantity = 1000
                        },
                        new
                        {
                            Id = 3,
                            Barcode = "3400935337700",
                            BatchNumber = "LOT003",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DrugId = 3,
                            ExpirationDate = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InitialQuantity = 300
                        },
                        new
                        {
                            Id = 4,
                            Barcode = "3400929200506",
                            BatchNumber = "LOT004",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DrugId = 4,
                            ExpirationDate = new DateTime(2027, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InitialQuantity = 200
                        },
                        new
                        {
                            Id = 5,
                            Barcode = "3400932832022",
                            BatchNumber = "LOT005",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DrugId = 5,
                            ExpirationDate = new DateTime(2026, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InitialQuantity = 400
                        },
                        new
                        {
                            Id = 6,
                            Barcode = "LOT006BCODE",
                            BatchNumber = "LOT006",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DrugId = 5,
                            ExpirationDate = new DateTime(2025, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InitialQuantity = 150
                        },
                        new
                        {
                            Id = 7,
                            Barcode = "LOT007BCODE",
                            BatchNumber = "LOT007",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DrugId = 5,
                            ExpirationDate = new DateTime(2027, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InitialQuantity = 600
                        });
                });

            modelBuilder.Entity("XpertPharm5Donation.Models.Dispensation", b =>
                {
                    b.HasOne("XpertPharm5Donation.Models.StockBatch", "StockBatch")
                        .WithMany("Dispensations")
                        .HasForeignKey("StockBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StockBatch");
                });

            modelBuilder.Entity("XpertPharm5Donation.Models.DonationVoucherLine", b =>
                {
                    b.HasOne("XpertPharm5Donation.Models.DonationVoucher", "DonationVoucher")
                        .WithMany("Lines")
                        .HasForeignKey("DonationVoucherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("XpertPharm5Donation.Models.Drug", "Drug")
                        .WithMany("VoucherLines")
                        .HasForeignKey("DrugId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("XpertPharm5Donation.Models.StockBatch", "StockBatch")
                        .WithMany()
                        .HasForeignKey("StockBatchId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DonationVoucher");

                    b.Navigation("Drug");

                    b.Navigation("StockBatch");
                });

            modelBuilder.Entity("XpertPharm5Donation.Models.StockBatch", b =>
                {
                    b.HasOne("XpertPharm5Donation.Models.Drug", "Drug")
                        .WithMany("StockBatches")
                        .HasForeignKey("DrugId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drug");
                });

            modelBuilder.Entity("XpertPharm5Donation.Models.DonationVoucher", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("XpertPharm5Donation.Models.Drug", b =>
                {
                    b.Navigation("StockBatches");

                    b.Navigation("VoucherLines");
                });

            modelBuilder.Entity("XpertPharm5Donation.Models.StockBatch", b =>
                {
                    b.Navigation("Dispensations");
                });
#pragma warning restore 612, 618
        }
    }
}
